### ISSUE TITLE
Add gender

### ISSUE THREAD

**Issue by CodeWritingCow** [bluzi/name-db#443] opened 2017-11-02 01:38 UTC
Hi @bluzi and everyone: Should we add `"sex"` or `"gender"` to the JSON file structure? 

Users might want to know whether a name is male, female or unisex. Especially if the name is from a language foreign to them.

Just a suggestion ...

**Comment by bluzi** [comment] 2017-11-02 17:58
Hey @CodeWritingCow,

I agree.
In your opinion, what would be the best way to implement it? We need to consider contributor's convenience and readability.

I mean, it could be something like: `male` `female` `unisex`, but it may cause trouble because or typos or people who write `females` or something like that. 
Alternatively, we could use numbers, such as: 0 = unisex, 1 = male, 2 = female. But that damages readability so I tend to go with the first option.

Any ideas?

**Comment by roastchicken** [comment] 2017-11-02 22:30
Single characters, such as `m`, `f`, and `u`, could reduce the incidence of misspellings while still keeping a decent amount of readability.

**Comment by CodeWritingCow** [comment] 2017-11-03 00:44
@roastchicken I was thinking the same thing. Single characters are a good compromise between using numbers and spelling entire words.

If we do use characters, we should explain the meanings of `m`, `f` and `u` in [readme.md](https://github.com/bluzi/name-db/blob/master/README.md).

**Comment by bluzi** [comment] 2017-11-03 19:13
Sounds good to me, I'm in!

Anyone wants to implement it and create a PR? 
You should:
- Update the documentation 
- Add a test
- Create an issue for adding genders

**Comment by CodeWritingCow** [comment] 2017-11-03 20:02
@bluzi I'll do it tonight!

**Comment by bluzi** [comment] 2017-11-03 21:14
Awesome!

**Comment by CodeWritingCow** [comment] 2017-11-04 04:51
Hi @bluzi, I implemented `sex` in my [fork's](https://github.com/CodeWritingCow/name-db/commit/929e3ebb705a86fa4b685c35a6adda7c7981adf6) readme.md and test.js. However, I'm having trouble making a PR.

This might be due to a previous PR that's open at #225 ... Can you close that PR for me? My apologies.

**Comment by bluzi** [comment] 2017-11-04 10:10
Hey @CodeWritingCow,

It looks like your PRs go mixed up, because you pushed everything to the master branch of your fork.
So all of your changes are at #225 

Anyway, that's fine, the problem is I cannot merge the change because the tests failing. That's probably because you made the sex field mandatory. I think it should be optional, at least until we have it in the whole collection.

**Comment by CodeWritingCow** [comment] 2017-11-04 19:05
Hi @bluzi,

I've commented out the `sex` field tests for now. All the other tests have passed.

**Comment by CodeWritingCow** [comment] 2017-11-06 07:09
Opened issue #456 for adding genders.

**Comment by CodeWritingCow** [comment] 2017-11-07 08:06
Hi @bluzi,

I followed your suggestion and made the field optional. If the field exists in a name field, then the test checks it for validity.

If the field contains only `""`, should it be allowed to pass the test? Some contributors might include `"sex": ""` if they aren't sure of a name's gender.

**Comment by bluzi** [comment] 2017-11-07 08:37
If you ask me, I think it should be illegal. If you don't know the sex, don't specify the sex property at all.

**Comment by roastchicken** [comment] 2017-11-07 13:54
I agree with @bluzi, the `sex` field should require a value.

**Comment by CodeWritingCow** [comment] 2017-11-08 04:05
@bluzi and @roastchicken, I updated the test so `sex` field is optional. But, if a file includes the `sex` field, then it cannot be empty.

**Comment by bluzi** [comment] 2017-11-09 23:26
Merged it, thanks a lot! @CodeWritingCow

**Comment by CodeWritingCow** [comment] 2017-11-10 02:23
@bluzi you are very welcome! Thanks for your patience.

**Comment by roastchicken** [comment] 2020-03-16 10:20
This was merged two years ago in #467. The architecture changes specifically were in the two commits [Add gender to name file specs](https://github.com/bluzi/name-db/pull/467/commits/929e3ebb705a86fa4b685c35a6adda7c7981adf6) and [Add tests to check validity of gender](https://github.com/bluzi/name-db/pull/467/commits/fcdacaed621a1c9a3c075378890e295de233ef6f).

The blames and logs are a bit confusing because there are two identically named pull requests with very similar commits, #467 and #474. But I believe the second, #474, was only to add `sex` fields to more names and didn't actually implement the architectural changes.

**Closed by roastchicken** 2020-03-16 10:20 UTC
Labels: enhancement, ideas
